### PR TITLE
A couple of methods

### PR DESCRIPTION
**Pull request by mickeyn**
Added more miscellaneous methods (for fetching favorite count and git repos).
Hope I didn't go the wrong way with the xt tree, just wanted to make some sense by making it go by argument type (and guessing we'll have to split the main Helper module accordingly soon enough :))

cheers,
Mickey

### CODE REVIEW

**Comment by neilbowers** [comment]
The 'release' directory under xt/ is for *release* testing, rather than referring to the MetaCPAN object type. Do you want to move things around, as a result?

**Comment by mickeyn** [comment]
Ah, sorry about that.
How would you like to structure it? I have no preference, just wanted to prepare for a lot more tests coming :)

**Comment by neilbowers** [comment]
I think we could go for release/distribution, release/release/, release/modules/.
I've never done an extra level, but I think that will work.

The only thing is that release/release/ is potentially confusing :-)

Are you really thinking of adding so many tests? If the total is only going to be ~20 files, then I don't think we need the extra level. But if much more than that, maybe yes.

**Comment by mickeyn** [comment]
Hehe, I meant many files as I hope to see many supported methods :)

I agree about the confusion, maybe we'll keep it flat under release for now (as it was originally in your first commit) and worry about structure when it actually grows bigger?

I'll work it out in the morning... off to bed now :)

**Comment by mickeyn** [comment]
closing this PR, will reopen a new one with the structure restored.

**Pull request closed without merging**
