### PR TITLE
More features: dist2favorite_count & release2git_repo

### PR DESCRIPTION
**Pull request by mickeyn**
Reopened with hopefully a better xt structure.

Cheers,
Mickey

### CODE REVIEW

**Comment by neilbowers** [comment]
The `release2git_repo` method should be called `release2repo`, since it doesn't have to be a github repo. There's a small number of dists that have non-git repos.

Plus I was expecting dist2repo, since that's normally what I'd look for (and I have a script doing that when assembling data for the PR challenge).

Which makes me wonder, if we had `dist2repo`, would it feel ok for it to take a MetaCPAN::Client *release* or *distribution*? They both refer to a dist, so it feels ok in a DWIM way, but might be confusing.

**Comment by mickeyn** [comment]
I don't mind the name change - will do that.
(it's not limited to Github BTW, just to git as in the Moose example - but I get your point)

The repos can change between release (I think) so I can add a dist2repo as a wrapper around release2repo fetching from the latest release.

**Comment by neilbowers** [comment]
> I can add a dist2repo as a wrapper around release2repo fetching from the latest release

works for me.

**Comment by mickeyn** [comment]
cool, will do.

**Pull request closed without merging**
